# Generated by Django 2.1.4 on 2021-05-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='test',
        ),
    ]
